# Generated by Django 3.0.7 on 2020-06-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_title', models.CharField(max_length=100)),
                ('post_content', models.CharField(max_length=400)),
                ('reported_user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blog',
                'managed': False,
            },
        ),
    ]
