# Generated by Django 3.0.7 on 2020-06-25 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_admins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'managed': False, 'ordering': ['-post_date']},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Blogs')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
