# Generated by Django 3.0.7 on 2020-06-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200625_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comments_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('comment_body', models.CharField(max_length=400)),
                ('comments_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
